In [1]:
import sys
import os
# setting path
sys.path.append(os.path.dirname(os.getcwd()))

In [2]:
import pandas as pd
import json
from src.getClean.json.GD_prov_jyhq import *

In [3]:
df_ls = load_files("../data/raw/Guangdong/prov_month")

In [4]:
output(df_ls, "../data/clean/Guangdong")

   Total_quant bid_diff avg_diff Bid_quant  Month  Year
0       130888             -7.36         0      1  2015
1       111913             -7.34         0      2  2015
2       131038    -3.49    -6.11     57000      3  2015
3       141014     -3.5    -6.15     57000      4  2015
4       148981    -3.47    -6.18     57000      5  2015
..         ...      ...      ...       ...    ...   ...
91                                              8  2022
92                                              9  2022
93                                             10  2022
94                                             11  2022
95                                             12  2022

[96 rows x 6 columns]

In [ ]:
with open("../data/raw/Guangdong/prov_month/jyhq_2022_GD.json", 'r') as f:
    data_2022 = json.load(f)
transfer(data_2022,1,12,2022)